### ISSUE TITLE
More Murdoch sites

### ISSUE THREAD

**Issue by elevingston** [gdunstone/MurdochOverlay#2]
List sourced from www.newscorpaustralia.com/brands/

"www.realestate.com.au/",
"www.vogue.com.au/",
"www.gq.com.au/",
"www.taste.com.au/",
"www.whimn.com.au/",
"www.bodyandsoul.com.au/",
"www.kidspot.com.au/",
"www.delicious.com.au/",
"www.bigrigs.com.au/",
"www.punters.com.au/",
"www.odds.com.au/",
"www.racenet.com.au/",
"www.broncos.com.au/",

**Comment by gdunstone** [comment]
This has been incorporated into version 1.4 on the mozilla addon store.

See commit https://github.com/gdunstone/MurdochOverlay/commit/88962c671d07e18a01c78b7a0af4496ff5ef6849
